- app/package.json
- app/yarn.lock
> Add(hangyeol/라이브러리 추가-develop):react-router-dom 과 emotion 라이브러리 설치 #2

- app/src/components/button/imgBtn/Alram.tsx
- app/src/components/button/imgBtn/Btn4.tsx
- app/src/components/button/index.tsx
- app/src/components/button/textBtn/Btn10.tsx
- app/src/components/button/textBtn/Btn11.tsx
- app/src/components/button/textBtn/Btn12.tsx
- app/src/components/button/textBtn/Btn5.tsx
- app/src/components/button/textBtn/Btn6.tsx
- app/src/components/button/textBtn/Btn7.tsx
- app/src/components/button/textBtn/Btn8.tsx
- app/src/components/button/textBtn/Btn9.tsx
-----------------------------------------
<모든 컴포 공통 반영>
commonSt -> commonStyle
difSt -> difStyles
ArrowFunc return 방식 수정
불필요한 React.Fragment 삭제
import { css, cx } from '@emotion/css'; 추가 후 index.tsx에서 삭제
-----------------------------------------
Btn1 변경 내역
1. 컴포명 Btn1 -> Alram
2. event -> able
Btn6 변경 내역
1. 이유 없는 function 선언 -> ArrowFunc로 수정 후 함수명 변경
-----------------------------------------
> Add(sungje/컴포넌트 생성-feature/components):버튼폴더 인덱스, 알람(Btn1), Btn4 생성

- app/src/components/button/imgBtn/Alram.tsx
- app/src/components/button/imgBtn/Btn4.tsx
- app/src/components/button/textBtn/Btn6.tsx
- app/src/components/button/textBtn/Btn7.tsx
Alram, Btn4, Btn6, Btn7 이미지 첨부 후 로직 수정하였습니다.
> Modify(sungje/feature-components):이미지가 들어가는 버튼들 수정 #10

- app/src/components/button/imgBtn/Alram.tsx
- app/src/components/button/imgBtn/Btn4.tsx
- app/src/components/button/index.tsx
- app/src/components/button/textBtn/Btn10.tsx
- app/src/components/button/textBtn/Btn11.tsx
- app/src/components/button/textBtn/Btn12.tsx
- app/src/components/button/textBtn/Btn5.tsx
- app/src/components/button/textBtn/Btn6.tsx
- app/src/components/button/textBtn/Btn7.tsx
- app/src/components/button/textBtn/Btn8.tsx
- app/src/components/button/textBtn/Btn9.tsx
1. 버튼 index에서 palette의 스타일을 import, export하는 코드 삭제.
2. Alram, Btn 컴포에 에 onClick props 추가 후 palette 스타일 import  경로 변경.
> Modify(susngje/feature-components): button/index & Btn컴포넌트들 수정

- app/src/components/button/imgBtn/Alram.tsx
- app/src/components/button/imgBtn/Btn4.tsx
- app/src/components/button/index.tsx
- app/src/components/button/textBtn/Btn10.tsx
- app/src/components/button/textBtn/Btn11.tsx
- app/src/components/button/textBtn/Btn12.tsx
- app/src/components/button/textBtn/Btn5.tsx
- app/src/components/button/textBtn/Btn6.tsx
- app/src/components/button/textBtn/Btn7.tsx
- app/src/components/button/textBtn/Btn8.tsx
- app/src/components/button/textBtn/Btn9.tsx
- app/src/components/category/Basic.tsx
- app/src/components/category/Category.tsx
- app/src/components/check-label/CheckLabel.tsx
- app/src/components/img-carousel/Img-carousel.tsx
- app/src/components/img-in-order/OrderedImg.tsx
- app/src/components/index.tsx
- app/src/components/markbox/MarkBox.tsx
- app/src/components/snap-scroll/Snap.tsx
- app/src/components/text-editor/Editor.tsx
- app/src/components/text/Text.tsx
- app/src/pages/home/Home.tsx
- app/src/styles/index.ts
- app/src/styles/layout/footer/Footer.tsx
- app/src/styles/layout/header/Header.tsx
- app/src/styles/layout/index.tsx
- app/src/styles/style/palette.ts
- 카테고리 사이즈 수정
- 메인 페이지 파트 1, 2 레이아웃 생성
> Modify(hangyeol/컴포넌트 생성-feature/components):메인 페이지 1, 2 파트 생성  #10

- app/src/components/category/Category.tsx
- app/src/components/img-in-order/OrderedImg.tsx
- app/src/components/img-in-order/style.ts
- app/src/components/newPost/NewPost.tsx
- app/src/pages/index.tsx
- app/src/pages/resign/index.tsx
- app/src/styles/layout/header/Header.tsx
- app/yarn.lock
Header.tsx > Btn6 컴포넌트 제거
redux 폴더, 내부 파일 제거
> Conflict(hangyeol/컴포넌트 생성-feature/components):conflict 해결  #10

- app/public/index.html
- app/src/components/img-carousel/Img-carousel.tsx
- app/src/components/img-in-order/OrderedImg.tsx
- app/src/components/img-in-order/style.ts
- app/src/components/index.tsx
- app/src/index.tsx
- app/src/pages/home/section1.tsx
- app/src/pages/mypage/OtherPage.tsx
- app/src/pages/resign/index.tsx
- app/src/pages/spec/Edit.tsx
- app/src/pages/spec/Visit.tsx
- app/src/pages/spec/index.tsx
- app/src/redux/root.tsx
- app/src/redux/user/reducer.tsx
- 캐러셀 버튼 위치 수정
- 스펙 모달 생성
- Category >> Categories, Category 분리
- 모달 props 수정 >> contents > children
> Merge(hangyeol/컴포넌트 생성-feature/components):스펙 모달 생성, 캐러셀 수정, 모달 props 수정, Categories 추가 및 수정 #10

- app/.prettierrc
- app/src/components/modal/QuitModal.tsx
- app/src/pages/login/login/Login.tsx
- app/src/pages/mypage/mypage/MySelf.tsx
- 개인정보 수정 페이지가 미완성인 관계로 MySelf.tsx 파일에 임시 렌더 시켜놨음
- 결과물 :
> [Add] 회원탈퇴 페이지 퍼블리싱 #115

- app/src/components/modal/QuitModal.tsx
- app/src/pages/login/login/Login.tsx
> [Fix] 사라진 파일 재 생성

- app/src/components/button/SelectBtn.tsx
- app/src/components/filter/Container.tsx
- app/src/components/filter/Presenter.tsx
- app/src/components/filter/Silder.tsx
- app/src/components/poster/Poster.tsx
- app/src/components/search/Input.tsx
- app/src/components/search/Presenter.tsx
- app/src/components/selectbox/SelectBox.tsx
- app/src/components/selectbox/SelectList.tsx
- app/src/pages/board/Board.tsx
1. 필터에서 정렬 항목 radio로 되게
2. SelectBox 열고 리스트에서 선택 시 리스트 닫히게
3. 게시글 필터링, 게시글 검색 기능
4. 필터 설정완료 버튼 누르면 필터창 닫히게
5. get요청으로 받은 게시글 이미지의 key 변경된 것 반영
6. 가격 설정 바 redux 반영 후 UI 버그 해결
7. 필터링된 게시물 요청 추가
> [Feature] 필터링 기능 반영 후 디테일 수정 #112

- app/src/components/category/Categories.tsx
- app/src/components/category/Category.tsx
- app/src/components/emptySpinner/EmptySpinner.tsx
- app/src/components/filter/Container.tsx
- app/src/components/filter/Presenter.tsx
- app/src/components/search/Container.tsx
- app/src/components/search/Input.tsx
- app/src/components/search/Presenter.tsx
- app/src/pages/board/Board.tsx
- app/src/redux/board/reducer.tsx
- app/src/styles/layout/header/Header.tsx
(app/src/components/filter/Container.tsx && app/src/components/search/Input.tsx 에 있던 onSubmit 함수 상위로 이동)
> [Feature] 게시판 작업

- app/src/apis/common/setInterceptors.ts
- app/src/apis/instance.tsx
- app/src/apis/postQuestion.tsx
- app/src/components/newPost/NewPost.tsx
- app/src/pages/faq/notice/Notice.tsx
- app/src/pages/faq/notice/NoticeCommentWrapper.tsx
- app/src/pages/inquire/inquire.tsx
- app/src/pages/login/login/Login.tsx
- app/src/pages/mypage/mypage/MySelf.tsx
- app/src/utils/getToken.ts
> Add(Feature/bumsoo/#133): access token refresh token 인증을 위한 인터셉터 구현 

- app/src/apis/comment.tsx
- app/src/apis/replies.tsx
- app/src/components/comment/Comment.tsx
- app/src/components/comment/CommentInputForm.tsx
- app/src/components/comment/CommentItem.tsx
- app/src/components/comment/CommentList.tsx
- app/src/components/comment/Commenter.tsx
- app/src/components/modal/ReportModal.tsx
- app/src/components/replies/Replier.tsx
- app/src/components/replies/Replies.tsx
- app/src/components/replies/RepliesInputForm.tsx
- app/src/components/replies/RepliesList.tsx
- app/src/components/replies/ReplyItem.tsx
- app/src/pages/post/Container.tsx
- app/src/pages/post/Presenter.tsx
- app/src/redux/comment/reducer.tsx
- app/src/redux/root.tsx
> [Feature] 댓글, 대댓글 작업

- app/src/components/comment/CommentItem.tsx
- app/src/components/mosaic/Mosaic.tsx
- app/src/components/newPost/NewPost.tsx
- app/src/components/profile/ModalProfile.tsx
- app/src/components/profile/Profile.tsx
- app/src/components/replies/ReplyItem.tsx
- app/src/pages/board/Board.tsx
- app/src/pages/createpost/Container.tsx
- app/src/pages/post/Btns.tsx
- app/src/pages/post/Container.tsx
- app/src/pages/post/PostWriter.tsx
- app/src/pages/post/Presenter.tsx
- app/src/redux/axios.tsx
- app/src/redux/mypage/reducer.tsx
1. 타 사용자 프로필 모달 생성
2. 사용자 프로필 이미지 리사이징 적용
3. 좋아요 API 인터셉터 적용
4. 모자이크 컴포넌트(비회원이 상세조회 시 콘텐츠 가리개) UI 수정
5. mypage/reducer 초기값 타입설정, 초기값으로 바꿔주는 reducer 생성 후 적용
6. 사용자 프로필 클릭 시 사용자 프로필 모달 띄워주기
> [Feature] 게시물 상세 조회 이슈

- app/src/components/category/Category.tsx
- app/src/components/popup/Popup.tsx
- app/src/components/poster/ImgBox.tsx
- app/src/components/search/Container.tsx
- app/src/pages/board/Board.tsx
- app/src/pages/login/findPassword/FindPassword.tsx
- app/src/pages/login/findPassword/Presenter.tsx
- app/src/pages/login/login/Login.tsx
- app/src/pages/post/Presenter.tsx
이 외에 로그인 시 메인으로 redirect 안되게
Popup 컴포넌트 수정, 게시판 Poster 컴포넌트 resizing 적용
> [Modify] 게시판 무한스크롤 수정

- app/src/pages/main/components/snap-scroll/Container.tsx
- app/src/pages/main/components/snap-scroll/Presenter.tsx
- app/src/types/main/snapScroll/type.ts
1.  Container / Presenter 분리
2. 파일 위치 변경
3. 컴포넌트 파일명 변경
> [Refactor] Main Page에서 사용하는 Snap 컴포넌트 리펙터링

- app/src/App.tsx
- app/src/components/img-in-order/OrderedImg.tsx
- app/src/components/img/Img.tsx
- app/src/components/input/createPost/input/Inputs.tsx
- app/src/components/postit/PostIt.tsx
- app/src/pages/createpost/Container.tsx
- app/src/pages/createpost/Presenter.tsx
- app/src/pages/createpost/component/imgs/Imgs.tsx
- app/src/pages/post/component/imgs/PostImgs.tsx
1. 수정 시 직렬적인 기존 이미지 요청을 병렬화 해서 진행
2. OrderedImgs 코드 리펙터링...그 외의 컴포넌트도 코드 리펙터링
3. 불필요한 파일 삭제
4. App.tsx 컴플릭 해결
> [Modify] 게시글 작성에서 사용하는 OrderedImg 이미지 로직 수정

- app/src/components/comment/Comment.tsx
- app/src/components/comment/CommentInputForm.tsx
- app/src/components/popup/Popup.tsx
- app/src/components/replies/Replies.tsx
- app/src/components/replies/RepliesInputForm.tsx
- app/src/pages/board/components/interactionPart/InteractionPart.tsx
- app/src/pages/login/findPassword/FindPassword.tsx
- app/src/pages/login/register/SelectInfo.tsx
- app/src/pages/post/Container.tsx
- app/src/pages/post/Presenter.tsx
- app/src/pages/post/component/infomation/Container.tsx
- app/src/pages/post/component/infomation/presenter/PostUserInteraction.tsx
- app/src/redux/modal/reducer.tsx
- app/src/types/comment/type.ts
- app/src/types/post/type.ts
- app/src/types/replies/type.ts
Popup 컴포넌트를 전역에서 상태관리 하려 함.
근데 dev 서버에서는 잘 작동을 하고 build 후 확인 해보니
Maximum call stack 오류가 남.
handlePopup() 이라는 action을 발생시켜 Popup의 view를 변환하고 있었는데,
이전에는 action에 children을 넣어 dispatch하고 있었음.
근데 그 children에는 Popup의 initialState를 변환 시키는 
즉, Popup을 닫는 dispatch(handlePopup())이 onClick으로 할당 되어 있는
Button children인데 그것이 call stack을 폭파시켜버린 것.
> [Bug] Product 서버에서 Popup 버그 해결

- app/src/apis/changePassword.tsx
- app/src/pages/login/findPassword/findPassword/Container.tsx
- app/src/pages/login/findPassword/findPassword/Presenter.tsx
- app/src/pages/login/findPassword/setNewPassword/Container.tsx
- app/src/pages/login/findPassword/setNewPassword/Presenter.tsx
- app/src/types/findPassword/type.ts
1. 비밀번호 찾기 모달 Container / Presenter 리펙터링
2. 새 비밀번호 설정 페이지 Container / Presenter 리펙터링
3. API : 비밀번호 찾기위해 이메일 전송하는 API, 새 비밀번호 설정 API 분리
4. Type : 비밀번호 찾기 모달, 새 비밀번호 설정 페이지 type 파일로 분리
> [Refactor] 비밀번호 찾기, 새 비밀번호 설정 페이지 리펙터링

- app/package.json
> [Feat] package.json 

- app/src/components/button/WhiteButton.tsx
- app/src/components/popup/Popup.tsx
- app/src/pages/createpost/Container.tsx
- app/src/pages/createpost/Presenter.tsx
- app/src/pages/post/component/summary/Summary.tsx
- app/src/types/createAndEditPost/type.ts
1. 게시글 작성이나 수정 시에 Popup이 뜨지 않던 이슈 해결
2. 게시글 상세 조회 페이지에서 XSS 방어를 위해 코드 수정
3. Popup 컴포넌트 UI 수정
> [Modify] 게시글 작성 페이지, 게시글 상세 조회 페이지, 팝업 수정

- app/src/components/button/Btn.tsx
- app/src/components/button/MainButton.tsx
- app/src/components/button/WhiteButton.tsx
- app/src/components/comment/Commenter.tsx
- app/src/components/focusBar/HalfBar.tsx
- app/src/components/profile/ModalProfile.tsx
- app/src/components/profileselect/PhoneNumberSelectBox.tsx
- app/src/components/replies/Replier.tsx
- app/src/pages/mypage/components/ModifyProfile/index.tsx
- app/src/pages/mypage/components/MyPage/MySelf.tsx
- app/src/pages/mypage/components/MyPage/OtherPage.tsx
- app/src/styles/layout/footer/Footer.tsx
- app/src/styles/layout/header/Header.tsx
1. Header, Footer 컴포넌트
2. 댓글, 대댓글, 마이페이지 컴포넌트
3. 공용 컴포넌트 등
> [Modify] :last-child -> :last-of-type으로 치환

- app/src/components/button/MainButton.tsx
- app/src/components/comment/CommentItem.tsx
- app/src/components/postit/PostIt.tsx
- app/src/components/replies/ReplyItem.tsx
- app/src/index.css
- app/src/pages/post/component/summary/Summary.tsx
- app/src/pages/post/component/writer/PostWriter.tsx
1. index.css 수정
2. 댓글 대댓글 텍스트 넘침 해결
3. 한 줄 요약 컴포넌트 리펙터링
> [Refactor] 게시글 상세 조회 수정

- app/src/pages/post/Presenter.tsx
- app/src/pages/post/component/quickMenu/QuickMenu.tsx
게시글 상세조회 Presenter에서 useScroll이라는 커스텀훅을 사용해 사용자가 일정 스크롤을 내리면
QuickMenu를 띄워주는 상황이였는데 그로 인해서 Presenter 내부 코드들이 커스텀훅으로 인해서 리렌더링이 계속 일어났던 상황.
그래서 useScroll 커스텀훅과 조건물을 QuickMenu로 옮겨 리렌더링을 최소화 시킴.
> [Refactor] useScroll() 커스텀 훅을 하위 컴포넌트로 이동

- app/src/components/search/Presenter.tsx
- app/src/pages/board/Container.tsx
1. 게시판 search/Presenter 컴포넌트 React.memo 적용
2. 게시판 board/Container에서 쿼리문에 할당하는 page nation 상태 reset 시켜주는 함수 useCallback 적용
> [Refactor] 게시판 리펙터링
